name: 'Terraform CI'

on: [push]

env:
  tf_version: 'latest'
  tf_working_dir: './src/'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'validate'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'plan'
          args: '-var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 'Terraform Destroy'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'destroy'
          args: '-var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
