name: 'Terraform CI'

on: [push]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: ./src/
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: ./src/
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: ./src/
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: ./src/
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          args: '-var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \ -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \ -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \ -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 'Terraform Destroy'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: ./src/
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'destroy'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
